### ISSUE TITLE
Instructions don't work with Firefox

### ISSUE THREAD

**Issue by Matthias247** [aurelia/beginner-kits#11]
I'm following the instructions from http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/getting-started to try out Aurelia. I'm using node.js http-server as described, since the open-in-firefox-approach gives lots of "not well-formed" error messages in the JS console.

However when I modify app.js and app.html with new content as described and reload the page I still see the old "Welcome to Aurelia!" content around. This even happens when I stop http-server and restart it. In chrome the new page immediatly appears after reload. I guess it's due to caching of the app.ts/html modules in firefox, but I don't know how to resolve that. Using the `-c-1` option of http-server do disable cache doesn't change anything.

Here is my configuration for reference:
Windows 7
Firefox 42
node 4.2.1

**Comment by EisenbergEffect** [comment]
It's an issue with Firefox. It is caching. Open deve tools, and go to settings. There's an advanced option to disable the cache while toolbox is open.
