### ISSUE TITLE
Typescript kit not working with routing tutorial

### ISSUE THREAD

**Issue by thebravedave** [aurelia/beginner-kits#12]
Hello, thank you for your hard work on this awesome looking framework!

I am having a hard time getting started. I downloaded the Typescript Kit from
http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/getting-started
and am following the tutorial, but am getting these errors when I get to the section on routing:
*******************************
"NetworkError: 404 Not Found - http://localhost/projects/aureliaskeleton/welcome.js"
ERROR [app-router]
Error: XHR error (404 Not Found) loading http://localhost/projects/aureliaskeleton/welcome.js Error loading http://localhost/projects/aureliaskeleton/welcome.js
ERROR [app-router] Router navigation failed, and no previous location could be restored.
***********************************

If I move my compiled welcome.js and welcome.html files one directory above the "src" folder (which is where they were before we renamed them as per the tutorial) then the project loads.
The tutorial does not describe this problem or what to do about it....

Any advice?

**Comment by EisenbergEffect** [comment]
We've found the issues and will get the fixes released soon. For the ts examples, please make sure the moduleId of the router looks like this `./welcome`.

**Comment by ahmelsayed** [comment]
I'm seeing the same thing when following the Getting Started guide. 
This is what my router config looks like (exactly the same as in the guide)

``` javascript
config.map([
    { route: ['', 'welcome'], name: 'welcome', moduleId: './welcome', nav: true, title: 'Welcome' },
    { route: 'users', name: 'users', moduleId: './users', nav: true, title: 'Github Users' }
]);
```

and the URLs in the navbar show as `http://127.0.0.1:8080/undefined`

these are the errors I'm seeing in the console

```
GET http://127.0.0.1:8080/welcome.js 404 (Not Found)
ERROR [app-router] Error: XHR error (404 Not Found) loading http://127.0.0.1:8080/welcome.js(…)
ERROR [app-router] Router navigation failed, and no previous location could be restored.
```

**Comment by PauloMiguel23** [comment]
I am also seeing the same error after following the TypeScript Getting Started guide. After adding the welcome.html and welcome.ts and creating a new app.html and app.ts, I reload the browser and get the error message:

```
[Mon, 11 Jan 2016 10:48:27 GMT] "GET /welcome.js" Error (404): "Not found"
```

**Comment by kritollm** [comment]
Thanks, './src/welcome' and './src/users' worked.
