### ISSUE TITLE
Production setup doesn't work when switching to Typescript

### ISSUE THREAD

**Issue by thebravedave** [aurelia/beginner-kits#13]
Hello, I was checking out your documentation on a production setup
http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.3/doc/article/a-production-setup
and  everything works up to "Running The App" section.
Yeoman generates the project for me.
I load the project and everything is working (the page loads, the navigation is there, each section of the navigation is working).  I then try to add a welcome.ts file to the project, and have it do everything that welcome.js did (welcome.js was part of the build yeoman acquired for me), and my IDE IntelliJ automatically compiled the typescript file for me, and now when I load the page and click on any of the navigation links that load with the page the url becomes "http://localhost:9000/undefined"
and the page shows a "Cannot GET /undefined" error.

Is there something special that has to be done if you are to use typescript?

**Comment by EisenbergEffect** [comment]
We are working on a new starter kit, designed specially for TypeScript. It's not quite ready yet (karma and protractor tests aren't running) but if you want, you can give it a go. I'll moving it to an official repo soon. For now, it's located here: https://github.com/cmichaelgraham/skeleton-navigation-typescript-vscode

**Comment by EisenbergEffect** [comment]
Actually, I went ahead and added it as an official repo: https://github.com/aurelia/skeleton-navigation-typescript

Again, there are some issues with it we are still working out, but it should get you up and running.
