### ISSUE TITLE
kit-typescript.zip `Error: Cannot read property 'match' of undefined(…)`

### ISSUE THREAD

**Issue by MrAndMrsK** [aurelia/beginner-kits#15]
Hosted in Visual Studio 2015, added as an existing *website*, browsed in latest Chrome 47.0.2526.106.  I tried debugging it for a minute but the cause isn't obvious to me.

```
DEBUG [aurelia] Loading plugin 
DEBUG [aurelia] Configured plugin 
DEBUG [aurelia] Loading plugin 
DEBUG [aurelia] Configured plugin 
DEBUG [aurelia] Loading plugin 
DEBUG [aurelia] Configured plugin 
DEBUG [aurelia] Loading plugin 
DEBUG [aurelia] Configured plugin 
DEBUG [aurelia] Loading plugin 
DEBUG [aurelia] Configured plugin 
INFO [aurelia] Aurelia Started
Error: Cannot read property 'match' of undefined(…)
```

![image](https://cloud.githubusercontent.com/assets/5518652/12020545/a70a924a-ad4b-11e5-9cf5-b52ad8993953.png)

**Comment by EisenbergEffect** [comment]
Can you zip up your project and attached it to this issue so I can have a look?

**Comment by MrAndMrsK** [comment]
I will attempt it again, but I made no changes from the download...

**Comment by MrAndMrsK** [comment]
I am attempting it again and along the way, there are at least three issues:

Within a reasonably short parent path like `c:\Users\myusername\Downloads\` I have the kit-typescript folder.  When I open it as a website in Visual Studio, the built-in npm integration kicks in (I guess) running `npm install` which downloads a bunch of packages - no errors.  But then when I attempt to RUN the website with <kbd>F5</kbd>, I get this output:

```text
------ Build started: Project: kit-typescript, Configuration: Debug Any CPU ------
Validating Web Site
Building directory '/jspm_packages/github/components/jquery@2.1.4/'.
Building directory '/jspm_packages/github/components/'.
Building directory '/jspm_packages/github/frankwallis/plugin-typescript@2.4.3/'.
	...
Building directory '/node_modules/aurelia-bundler/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/lib/'.
Building directory '/node_modules/aurelia-bundler/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/commander/node_modules/graceful-readlink/'.
Building directory '/node_modules/aurelia-bundler/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/commander/'.
	...
Building directory '/node_modules/aurelia-bundler/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/tryor/'.
Building directory '/node_modules/aurelia-bundler/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/yargs/lib/'.
Building directory '/node_modules/aurelia-bundler/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/yargs/node_modules/camelcase/'.
: Build (web): The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
```

None of the complete pathnames shown are very near that limit (although they maybe should be shorter anyway for this consideration, as ridiculous as the limit is).  It is the NEXT path which wasn't yet emitted to the log - once I retry from scratch at the shorter path `c:\kit-typescript\`, I see that after `camelcase` is `Building directory '/node_modules/jspm/node_modules/uglify-js/node_modules/yargs/node_modules/cliui/node_modules/center-align/node_modules/align-text/node_modules/kind-of/node_modules/is-buffer/test/'`.  That path isn't too long either, nor is the path of its only contained file `basic.js`, but maybe the build script tests for a path there which is too long?

2) Core.js bundled with this is the version that uses `$` in the file names which TFS can't take.  Leads to an awful and unusable UI experience as depicted below which happens upon every opening of the website sln in VS2015 (logged as a UI bug with them too).  core-js 2 renamed those files for that reason but I even had trouble forcing the upgrade because version caps elsewhere that I didn't know enough about.  Btw, why is core-js required?

![tfs bug](https://cloud.githubusercontent.com/assets/5518652/12100456/0e4f3bd4-b2fd-11e5-9d65-adee69fa6491.gif)

As with the path name length limit of Windows, it's so ridiculous that TFS can't handle arbitrary file names, but it can't - and I don't think I'm the only prospective Aurelia user with this prescribed setup.

3) Once I move to the shorter path `c:\kit-typescript\` and not to a TFS-controlled folder, it builds and starts IIS Express successfully.  But the browser console gives an error `http://localhost:7375/tsconfig.json - Failed to load resource: the server responded with a status of 404 (Not Found)` because in fact there is no tsconfig.json.  If I run `tsc -init` in `kit-typescript` to create it and try to browse again, then finally I see "Welcome to Aurelia!" and no console errors.

I don't know why I got the `match` not defined issue last week.  It was probably because of either the TFS or path length issues, but I think I would have noticed that they were the blocking issue (I noticed them but I didn't see them as causing *this* issue).

# So ...

I guess I'm asking that:

  1. These app starter kits should lose some of the overhead and build process involved.  Consuming applications shouldn't be burdened with the build of aurelia from source.  Can't the aurelia package just have the debug and minified files?  This should also resolve the path length issue.
  2. I'm also confused about the intent of the Typescript aspect of this including a typescript transpiler.  Is that what it's doing?  Typescript to js on the client side?  I can't think of a situation where it would be appropriate to have this setup.  I mean, *maybe* some optional shim for ES6 to ES5 in a year or two once ES6 adoption is in the majority.  But typescript is very unlikely to be embedded in browsers as a javascript alternative.  And anyway, I really doubt that client-side typescript compilation is what aurelia experimenters are interested in.  I assume that most developers would just be looking for a kit that includes the `.d.ts` files along with a Visual Studio configuration and file organization that makes sense in a publisher-built typescript language workflow.  Something like, "TS files go here, typing files go here, they compile to there and this gulp script (or whatever) copies only the files that are needed by the client into the wwwroot folder where the client side module system knows how to find them thusly..."
  3. Upgrade to Core.js 2 if it's even still necessary to keep to allow compatibility for developers shackled to TFS-style version control.

I'm aware that this post may represent multiple issues which I'm happy to split out.  If I get your thoughts first about which things are already on the roadmap or which things are wrong or irrelevant or accounted for or have additional background or whatever I can add other issues to the right spots accordingly.

It is a neat project!  Thanks for making it.

**Comment by Gheoan** [comment]
Upgrading to `npm` 3 should fix the long paths issue.
The `core-js` upgrade is probably on the way: https://github.com/aurelia/framework/issues/282.

**Comment by Gheoan** [comment]
The `tsconfig.json` file is included https://github.com/aurelia/beginner-kits/blob/master/kit-typescript/tsconfig.json

**Comment by EisenbergEffect** [comment]
@MrAndMrsK Sorry about the problems you are having. We'll get core.js fixed up in the near future. Regarding the beginner kits, these are designed strictly to help get up and running without needing to install anything, to help new developers learn and try out the framework. For real application development, you'll want to use one of our production-ready skeletons. Those are also set up with build and bundling options. No transpilers are running in the browser for those. Information here: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.7/doc/article/a-production-setup

**Comment by MrAndMrsK** [comment]
@Gheoan - thanks for the tip about the upgrade of npm and the reference to the existing core-js dependency issue.  The kit.zip I still have does not include the tsconfig.json but a fresh downloaded copy does.  I don't know if somehow I fat-finger deleted that file out of the zip archive or what but it is missing in my original copy.

**Comment by MrAndMrsK** [comment]
@EisenbergEffect - ok thanks for clearing up those things for me.  Looking back at the Docs, I see now that there is a kit vs a skeleton, but I had no idea coming into it that there even would be those differences to look for them and the look of it is SO similar:

![image](https://cloud.githubusercontent.com/assets/5518652/12118739/21288fe6-b396-11e5-8cd3-2e6c886a6f05.png)

... in case you agree that it is non-obvious and in case anything could be done to clear it up.  But I'm settled now.  Thanks.

**Comment by EisenbergEffect** [comment]
Yes, abosolutely agree. We need to make this clearer. In the long term, this will become very different since we won't have skeletons, but rather a new project wizard that will let you select various options for your production kit and we will build a custom kit for you. For now, we have some pre-fab solutions. We'll try to do some improvements to the docs to make this more clear for the next release.
