### ISSUE TITLE
Uncaught (in promise) Error: Error: Plugin

### ISSUE THREAD

**Issue by SteveHartzog** [aurelia/beginner-kits#18]
When doing a jspm install or update on the kit-typescript (which is based on an early build of beta 1 (not the early March build) and starting the site, I receive the following error:

```
Uncaught (in promise) Error: Error: Plugin http://127.0.0.1:8080/src/jspm_packages/github/frankwallis/plugin-typescript@2.6.0.ts cannot load itself, make sure it is excluded from any wildcard meta configuration via a custom loader: false rule.
	Error loading http://127.0.0.1:8080/src/jspm_packages/github/frankwallis/plugin-typescript@2.6.0.ts
	Error loading http://127.0.0.1:8080/src/jspm_packages/npm/aurelia-bootstrapper@1.0.0-beta.1.1.1.ts
```

I've tried rolling back the new aurelia-loader & aurelia-bootstrap (as the error above notes) with no success.

**Comment by EisenbergEffect** [comment]
Don't run jspm or npm against the beginner kits. They are not built to work for that. If you want to do that, use one of the production starter kits, please.

Frank's TS plugin is especially picky. It breaks all the time...just about every other release in my experience. I don't recommend using that outside of our "get up and running quick" scenario.

**Comment by jj09** [comment]
I got this error (without running jspm install) when using Chrome and going to http://localhost:8080
When using http://127.0.0.1:8080 (on Chrome) - it works
It also work with Safari on both http://localhost and http://127.0.0.1

Maybe this is an issue with http-server?
