### ISSUE TITLE
Gulp tasks not included in beginner kit

### ISSUE THREAD

**Issue by samirbr** [aurelia/beginner-kits#19]
If you download the beginner's kit and follow the instructions starting with Get Started, and following up to [A Production Setup](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.4/doc/article/a-production-setup) you can't progress without gulp tasks unless you look for it in Aurelia skeleton-navigate.

There is no clear information on A Production Setup how to get gulp tasks for the beginner kit.

My suggestion is either add information in how to get gulp tasks for the project or include in the project/zip file.

**Comment by EisenbergEffect** [comment]
The beginner kit isn't designed to evolve into the production kit. They are for two different scenarios. That said, we are working on a new CLI that will replace both of these options for most people. So, we'll address the issue that way soon.

**Comment by samirbr** [comment]
Thanks :+1:
