### ISSUE TITLE
Aurelia without jspm?

### ISSUE THREAD

**Issue by nojaf** [aurelia/beginner-kits#2]
Not sure if this is the right repo but I was wondering if it's possible to use aurelia without jspm?
I'd rather like to download all the packages from npm and use [rollupjs](http://rollupjs.org/) or browserify to create a bundle and run my code.

Is this possible? Could somebody perhaps point me in the right direction to do this. Thanks

**Comment by EisenbergEffect** [comment]
Not really the right repo, but that's ok. (The beginner kits are designed to "just work" and not require extra tooling. They aren't meant for production app developer, but more for learning and exploring.)

Is it possible to use aurelia without JSPM? Yes. You could install everything with Bower as well. JSPM/Bower is just the package manager. In the end I think you are asking about module loading and bundling. With respect to loading, there needs to be an ES6-ish module loader present. Aurelia works with System.js and require-based APIs (like require.js and dojo loader) out of the box. But it's possible to implement your own loader. The main thing is that Aurelia is designed around writing ES6 modules for components....and those modules need to be preserved semantically at runtime, including when things are bundled. I haven't looked deeply into rollupjs, but I think it erases the modules, which would break Aurelia. (It's no longer really spec-compliant ES6 code.) I haven't checked browserify either so I don't know about that.

But the main consideration is can you bundle your app and ensure that the module loader calls still work. If you want to try to build a custom loader for one of these scenarios, we could assist you along the way.

**Comment by EisenbergEffect** [comment]
Did some more research, with respect to rollupjs, read this: https://github.com/rollup/rollup#how-does-this-compare-to-jspmsystemjs

This indicates what I suspect which is that rollupjs is better suited to bundling libraries, rather than apps. So, Aurelia itself could use rollupjs but that wouldn't necessarily be what you want to do for your app.

**Comment by nojaf** [comment]
I see, thanks for the effort.
