### ISSUE TITLE
Duplicate Identifier errors when compiling Typescript kit

### ISSUE THREAD

**Issue by zeronymous** [aurelia/beginner-kits#20]
According to the "Getting Started" guide at [http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/getting-started](http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/getting-started), the kit should be able to be used as is, but after downloading and extracting, invoking tsc produces a couple thousand errors that look like 

> 
jspm_packages/npm/typescript@1.7.5/lib/lib.core.d.ts(83,5): error TS2300: Duplicate identifier 'configurable'.

Typescript version 1.8.9

**Comment by EisenbergEffect** [comment]
The kit doesn't require tsc precompile and is designed to work without it.
If you want to invoke tsc directly you need to use a production kit.
