### ISSUE TITLE
Beta1 - importing only html custom element problem 

### ISSUE THREAD

**Issue by wasimf** [aurelia/beginner-kits#3]
Hi,

I'm trying the Beta 1 (Ts template) and have a problem with two issues ::

1.  require from="nav-bar.html" its requires nav-bar.html.ts
2.   the routes don't work till I add src , for example src/welcome . if its a bug please fix it in the documentation.

Thanks...

**Comment by PWKad** [comment]
@EisenbergEffect I think this is an issue in the config.js - https://github.com/aurelia/beginner-kits/blob/master/kit-typescript/config.js#L16 - that overrides everything in `src`.

**Comment by wasimf** [comment]
Should fix anything in config.js ?

**Comment by EisenbergEffect** [comment]
If you configure the module id of the router like this `./welcome` it will fix issue 2. Issue 1 is a bug in the loader itself. We've added some configuration and done some defensive coding on our end to work around this. Both these issues will be addressed in the next release.
