### ISSUE TITLE
TypeScript | Getting Started - all file names in the docs have '.js' extension

### ISSUE THREAD

**Issue by mickeyvip** [aurelia/beginner-kits#6]
As we are in the TypeScript and the sources are written in TypeScript, I would expect the files to have `.ts` extension.

**Comment by EisenbergEffect** [comment]
I don't see anything but .ts. Where are you seeing other things?

**Comment by mickeyvip** [comment]
I am referring to the docs only, not the sources

**Comment by mickeyvip** [comment]
![image](https://cloud.githubusercontent.com/assets/220427/11324583/291aead4-913e-11e5-9f54-7ed70c59f76f.png)

**Comment by EisenbergEffect** [comment]
We will have a fix for this in the next docs release.
