### ISSUE TITLE
TypeScript | Getting Started - none of the modules can be fetched (404)

### ISSUE THREAD

**Issue by mickeyvip** [aurelia/beginner-kits#7]
Following the docs I see that none of the new written modules can be fetched (404).

The reason is that the files are configured to be under `app`, so only `app/module_name` will be fetched as `/src/module_name.ts`.

As per the docs: `moduleId: "module_name"` - will be fetched as `/module_name.js`, which does not exist.

The same is with `<require from="nav-bar"></require>`, which should be `<require from="app/nav-bar"></require>`

**Comment by EisenbergEffect** [comment]
We've made some fixes in our docs, going out in the next docs release. Try configuring the routes with module ids like `./welcome`.
